AMOLED-Cord V4
LuckFire/amoled-cord pull request #52
Opened 2023-03-24 16:51 UTC by LuckFire

This PR is v4 of AMOLED-cord. The main purpose of the rewrite is primarily for the file structuring, however, you will be able to tell that the theme is noticeably darker as well.

2023-03-24 21:24 UTC, FedeIlLeone requested changes

2023-03-24 21:24 UTC, FedeIlLeone commented on src/theme/sidebar/_user-area.scss
- Voice channel buttons are invisible.

2023-03-24 22:03 UTC, LuckFire commented on src/theme/settings/_guild.scss
> I don't know if it's necessary to do this, but the previews with the light theme for roles and stickers are visible. 
> Audit log filters popout.
Can you elaborate for these ones a bit? (I understand the sticker preview one for the first one though)

2023-03-24 22:11 UTC, FedeIlLeone commented on src/theme/settings/_guild.scss
![IMG_20230324_231112.jpg](https://user-images.githubusercontent.com/38290480/227652843-1f5b9ce3-7cc5-4835-8408-c0ad0ecd356f.jpg)

2023-03-24 22:15 UTC, LuckFire commented on src/theme/settings/_guild.scss
Is it unthemed or not themed properly?

2023-03-24 22:17 UTC, FedeIlLeone commented on src/theme/settings/_guild.scss
It's completely black

2023-03-25 22:21 UTC, LuckFire commented
I think I've covered everything that needs to be covered (ignoring any plugins from client mods, I'll make sure to get those as they're reported).

2023-03-26 08:50 UTC, FedeIlLeone reviewed
Some more stuff

2023-03-26 08:50 UTC, FedeIlLeone commented on src/theme/popouts/_index.scss
- Warning when sending @ everyone in a 100+ server members.
![image](https://user-images.githubusercontent.com/38290480/227764163-744b64ed-c25c-4c13-9b64-a46c734fefaf.png)
- Favorite GIFs.
![image](https://user-images.githubusercontent.com/38290480/227764257-9117e9ce-28ee-4dbd-9ff5-de1b8da08bd3.png)
- Country code picker.
![image](https://user-images.githubusercontent.com/38290480/227765228-940e460f-ebb3-4f64-8f02-4d49a4a087b5.png)
- Select menu when adding a server to a hub (`popout-15UxD6`).
![image](https://user-images.githubusercontent.com/38290480/227764482-6774c3d5-3447-427d-8059-93c6e4b49f0b.png)

2023-03-26 08:50 UTC, FedeIlLeone commented on src/theme/settings/_index.scss
- All X buttons (emojis, server notification settings, hidden games library).

2023-03-27 17:00 UTC, LuckFire commented on src/theme/popouts/_index.scss
I'm not able to theme the @everyone picker, country code picker, and select menu for when adding a server hub (since I'm unable to directly access them). I could guess with the classes given, but it's best for me to have direct access to them so I can theme them well.

2023-03-29 03:12 UTC, LuckFire commented
Let me know if everything looks good when you get the chance

2023-03-29 20:26 UTC, FedeIlLeone commented
> Let me know if everything looks good when you get the chance

LGTM.

2023-03-29 20:37 UTC, merged